script: |
            # 1. Заходим в папку с репозиторием
            cd /root/bots-fish/bots-fish
            
            # 2. ЖЕСТКО сбрасываем локальные изменения и качаем с гитхаба
            git fetch --all
            git reset --hard origin/main
            
            # 3. Убиваем старые процессы ботов (упростил команду без кавычек)
            pkill -f bot1/bot.py  true
            pkill -f bot2/bot2.py  true
            
            # 4. Запускаем первого бота
            nohup /root/bots-fish/bots-fish/venv/bin/python /root/bots-fish/bots-fish/bot1/bot.py > /root/bots-fish/bots-fish/bot1/log.txt 2>&1 &
            
            # 5. Запускаем второго бота
            nohup /root/bots-fish/bots-fish/venv/bin/python /root/bots-fish/bots-fish/bot2/bot2.py > /root/bots-fish/bots-fish/bot2/log.txt 2>&1 &
